Bail if one of the docker builds fails

diff --git a/build b/build
--- a/build
+++ b/build
@@ -14,6 +14,14 @@ BRANCHES[libvigor]=master
 PACKAGES=()
 TARGETS=()
 
+bail() {
+  echo >&2
+  echo >&2 "FAIL!"
+  echo >&2 $*
+  echo >&2
+  exit 2
+}
+
 while [[ $# != 0 ]]; do
   case "${1}" in
   (ctap|libsodium|libvigor|libzmq|autotools)
@@ -60,10 +68,12 @@ for package in ${PACKAGES[@]}; do
   for target in ${TARGETS[@]}; do
     if [[ -n ${USE_BRANCH} ]]; then
       echo "building ${package} (branch ${USE_BRANCH}) in ${target}"
-      docker run -it -e BRANCH=${USE_BRANCH} -e VERSION=${VERSIONS[${package}]} -v ${BASE}/${package}:/srv ${target}:latest
+      docker run -it -e BRANCH=${USE_BRANCH} -e VERSION=${VERSIONS[${package}]} -v ${BASE}/${package}:/srv ${target}:latest || \
+        bail "unable to build ${BASE}/${package} (branch ${USE_BRANCH}) in ${target}"
     else
       echo "building ${package} in ${target}"
-      docker run -it -e VERSION=${VERSIONS[${package}]} -v ${BASE}/${package}:/srv ${target}:latest
+      docker run -it -e VERSION=${VERSIONS[${package}]} -v ${BASE}/${package}:/srv ${target}:latest || \
+        bail "unable to build ${BASE}/${package} in ${target}"
     fi
     echo; echo; echo; echo;
   done
